Repository Human-Connection/Nitro-Backend, pull requests merged in 2019-01, with the labels that each got.

#88 Login: Friendly error message if email is incorrect
  .eslintrc.js
  README.md
  package.json
  src/graphql-schema.js
  src/graphql-schema.test.js
  src/index.js
  src/middleware/permissionsMiddleware.test.js
  src/seed/factories/index.js
  src/seed/factories/users.js
  src/server.js
  yarn.lock
Labels: PR: reviewed-approved

#93 FIX #49 capture error in readable format with try and catch
  src/graphql-schema.js
Labels: PR: reviewed-approved

#100 Update README.md
  README.md
Labels: PR: reviewed-approved

#108 Don't run tests in /dist folder
  package.json
Labels: PR: reviewed-approved

#104 fix #41 jwt strategy
  src/jwt/strategy.js
  src/server.js
Labels: PR: reviewed-approved, bug

#109 106 authorization
  .travis.yml
  README.md
  dist/.gitkeep
  package.json
  scripts/test.sh
  src/graphql-schema.spec.js
  src/jest/helpers.js
  src/middleware/passwordMiddleware.js
  src/middleware/permissionsMiddleware.spec.js
  src/middleware/permissionsMiddleware.test.js
  src/middleware/userMiddleware.js
  src/seed/data/index.js
  src/seed/factories/index.js
Labels: PR: reviewed-approved

#115 Import remote mongodb in neo4j
  .dockerignore
  db-migration-worker/.gitignore
  db-migration-worker/.ssh/.dockerignore
  db-migration-worker/.ssh/known_hosts
  db-migration-worker/Dockerfile
  db-migration-worker/import.sh
  docker-compose.override.yml
  docker-compose.yml
  neo4j/Dockerfile
  neo4j/import/comments.cql
  neo4j/import/contributions.cql
  neo4j/import/import.sh
  neo4j/import/todo
  neo4j/import/users.cql
  src/middleware/fixImageUrlsMiddleware.js
  src/middleware/fixImageUrlsMiddleware.spec.js
  src/seed/reset-db.js
Labels: PR: reviewed-approved

#99 Report content
  src/graphql-schema.js
  src/middleware/permissionsMiddleware.js
  src/schema.graphql
  src/seed/data/index.js
  src/seed/data/reports.js
  yarn.lock
Labels: PR: reviewed-approved, feature

#131 Move troubleshoots to end; add install links for docker and minikube
  .gitignore
  kubernetes/README.md
Labels: PR: reviewed-approved

#127 Follow up on data import
  .dockerignore
  .gitignore
  db-migration-worker/Dockerfile
  db-migration-worker/import.sh
  docker-compose.override.yml
  neo4j/import/badges.cql
  neo4j/import/categories.cql
  neo4j/import/follows.cql
  neo4j/import/import.sh
  neo4j/import/shouts.cql
  neo4j/import/todo
  public/.gitkeep
  public/img/badges/fundraisingbox_de_airship.svg
  public/img/badges/fundraisingbox_de_alienship.svg
  public/img/badges/fundraisingbox_de_balloon.svg
  public/img/badges/fundraisingbox_de_bigballoon.svg
  public/img/badges/fundraisingbox_de_crane.svg
  public/img/badges/fundraisingbox_de_glider.svg
  public/img/badges/fundraisingbox_de_helicopter.svg
  public/img/badges/fundraisingbox_de_starter.svg
  public/img/badges/indiegogo_en_bear.svg
  public/img/badges/indiegogo_en_panda.svg
  public/img/badges/indiegogo_en_rabbit.svg
  public/img/badges/indiegogo_en_racoon.svg
  public/img/badges/indiegogo_en_rhino.svg
  public/img/badges/indiegogo_en_tiger.svg
  public/img/badges/indiegogo_en_turtle.svg
  public/img/badges/indiegogo_en_whale.svg
  public/img/badges/indiegogo_en_wolf.svg
  public/img/badges/user_role_admin.svg
  public/img/badges/user_role_developer.svg
  public/img/badges/user_role_moderator.svg
  public/img/badges/wooold_de_bee.svg
  public/img/badges/wooold_de_butterfly.svg
  public/img/badges/wooold_de_double_rainbow.svg
  public/img/badges/wooold_de_end_of_rainbow.svg
  public/img/badges/wooold_de_flower.svg
  public/img/badges/wooold_de_lifetree.svg
  public/img/badges/wooold_de_magic_rainbow.svg
  public/img/badges/wooold_de_super_founder.svg
  src/middleware/fixImageUrlsMiddleware.js
  src/middleware/fixImageUrlsMiddleware.spec.js
  src/server.js
Labels: PR: unreviewed
